openapi: '3.0.3'
info:
  title: Vibin' API
  description: API for the Vibin' music server
  version: 0.0.1
  contact:
    name: "Vibin' Project"
    url: "https://github.com/mickkc/vibin"
    email: "tim@vibin.wtf"
  license:
    name: Licensed under VPL v1.0
    url: "https://github.com/mickkc/vibin/blob/main/LICENSE.md"
servers:
  - url: 'http://localhost:8080'
paths:
  
  # ▄▀█ █░█ ▀█▀ █░█
  # █▀█ █▄█ ░█░ █▀█

  /api/auth/login:
    $ref: 'methods/auth.yaml#/Login'

  /api/auth/validate:
    $ref: 'methods/auth.yaml#/Validate'

  /api/auth/logout:
    $ref: 'methods/auth.yaml#/Logout'

  # █▀▄▀█ █▀▀ █▀▄ █ ▄▀█ ▀█▀ █▀█ █▄▀ █▀▀ █▄░█
  # █░▀░█ ██▄ █▄▀ █ █▀█ ░█░ █▄█ █░█ ██▄ █░▀█

  /api/auth/media/token:
    $ref: 'methods/mediaTokens.yaml#/MediaToken'

  /api/auth/media:
    $ref: 'methods/mediaTokens.yaml#/Validate'

  # █▀ █▀▀ █▀ █▀ █ █▀█ █▄░█ █▀
  # ▄█ ██▄ ▄█ ▄█ █ █▄█ █░▀█ ▄█

  /api/auth/sessions:
    $ref: 'methods/sessions.yaml#/GetAll'

  /api/auth/sessions/{sessionId}:
    $ref: 'methods/sessions.yaml#/Invalidate'

  /api/auth/sessions/all:
    $ref: 'methods/sessions.yaml#/InvalidateAll'
  
  # ▄▀█ █░░ █▄▄ █░█ █▀▄▀█ █▀
  # █▀█ █▄▄ █▄█ █▄█ █░▀░█ ▄█

  /api/albums:
    $ref: 'methods/albums.yaml#/Base'

  /api/albums/{id}:
    $ref: 'methods/albums.yaml#/Id'

  /api/albums/artists/{id}:
    $ref: 'methods/albums.yaml#/ByArtist'

  /api/albums/{id}/cover:
    $ref: 'methods/albums.yaml#/Cover'
  
  # ▄▀█ █▀█ ▀█▀ █ █▀ ▀█▀ █▀
  # █▀█ █▀▄ ░█░ █ ▄█ ░█░ ▄█
  
  /api/artists:
    $ref: 'methods/artists.yaml#/Base'
  
  /api/artists/{id}:
    $ref: 'methods/artists.yaml#/Id'

  /api/artists/ids:
    $ref: 'methods/artists.yaml#/Ids'
  
  /api/artists/autocomplete:
    $ref: 'methods/artists.yaml#/Autocomplete'

  # █▀▀ █░█ █▀▀ █▀▀ █▄▀
  # █▄▄ █▀█ ██▄ █▄▄ █░█

  /api/check:
    $ref: 'methods/check.yaml#/Check'

  # █▀▀ ▄▀█ █░█ █▀█ █▀█ █ ▀█▀ █▀▀ █▀
  # █▀░ █▀█ ▀▄▀ █▄█ █▀▄ █ ░█░ ██▄ ▄█

  /api/favorites/{id}:
    $ref: 'methods/favorites.yaml#/Get'

  /api/favorites/{type}/{place}:
    $ref: 'methods/favorites.yaml#/Toggle'

  /api/favorites/{type}/check/{entityId}:
    $ref: 'methods/favorites.yaml#/Check'

  # █▀▄▀█ █▀▀ ▀█▀ ▄▀█ █▀▄ ▄▀█ ▀█▀ ▄▀█
  # █░▀░█ ██▄ ░█░ █▀█ █▄▀ █▀█ ░█░ █▀█

  /api/metadata/providers:
    $ref: 'methods/metadata.yaml#/Providers'

  /api/metadata/{type}:
    $ref: 'methods/metadata.yaml#/Fetch'

  /api/metadata/create:
    $ref: 'methods/metadata.yaml#/Create'

  # █▀▄▀█ █ █▀ █▀▀
  # █░▀░█ █ ▄█ █▄▄

  /api/misc/welcome:
    $ref: 'methods/misc.yaml#/Welcome'

  # █▀█ █▀▀ █▀█ █▀▄▀█ █ █▀ █▀ █ █▀█ █▄░█ █▀
  # █▀▀ ██▄ █▀▄ █░▀░█ █ ▄█ ▄█ █ █▄█ █░▀█ ▄█

  /api/permissions:
    $ref: 'methods/permissions.yaml#/GetCurrent'

  /api/permissions/{userId}:
    $ref: 'methods/permissions.yaml#/ForUser'

  # █▀█ █░░ ▄▀█ █▄█ █░░ █ █▀ ▀█▀ █▀
  # █▀▀ █▄▄ █▀█ ░█░ █▄▄ █ ▄█ ░█░ ▄█

  /api/playlists:
    $ref: 'methods/playlists.yaml#/Base'

  /api/playlists/{id}:
    $ref: 'methods/playlists.yaml#/Id'
  
  /api/playlists/{id}/image:
    $ref: 'methods/playlists.yaml#/Image'
  
  /api/playlists/random:
    $ref: 'methods/playlists.yaml#/Random'

  /api/playlists/{playlistId}/tracks:
    $ref: 'methods/playlistTracks.yaml#/Base'

  /api/playlists/containing/{trackId}:
    $ref: 'methods/playlistTracks.yaml#/ContainingTrack'

  # █▀ █▀▀ ▀█▀ ▀█▀ █ █▄░█ █▀▀ █▀
  # ▄█ ██▄ ░█░ ░█░ █ █░▀█ █▄█ ▄█
  
  /api/settings/server:
    $ref: 'methods/settings.yaml#/Server'

  /api/settings/user:
    $ref: 'methods/settings.yaml#/User'
  
  /api/settings/{key}:
    $ref: 'methods/settings.yaml#/Update'

  # █▀ ▀█▀ ▄▀█ ▀█▀ █▀
  # ▄█ ░█░ █▀█ ░█░ ▄█

  /api/stats/recent:
    $ref: 'methods/stats.yaml#/Recent'

  /api/stats/{type}/top{limit}:
    $ref: 'methods/stats.yaml#/Top'

  /api/stats/listen/{type}/{id}:
    $ref: 'methods/stats.yaml#/Report'
  
  /api/stats/users/{id}/activity:
    $ref: 'methods/stats.yaml#/Activity'

  /api/stats/global:
    $ref: 'methods/stats.yaml#/Global'

  # ▀█▀ ▄▀█ █▀▀ █▀
  # ░█░ █▀█ █▄█ ▄█

  /api/tags:
    $ref: 'methods/tags.yaml#/Base'
  
  /api/tags/{id}:
    $ref: 'methods/tags.yaml#/Id'
  
  /api/tags/ids:
    $ref: 'methods/tags.yaml#/Ids'
    
  /api/tags/named/{name}:
    $ref: 'methods/tags.yaml#/ByName'
  
  /api/tags/check/{name}:
    $ref: 'methods/tags.yaml#/CheckName'

  # ▀█▀ ▄▀█ █▀ █▄▀ █▀
  # ░█░ █▀█ ▄█ █░█ ▄█

  /api/tasks:
    $ref: 'methods/tasks.yaml#/Get'

  /api/tasks/{taskId}/enable:
    $ref: 'methods/tasks.yaml#/Enable'

  /api/tasks/{id}/run:
    $ref: 'methods/tasks.yaml#/Run'

  # █░█ █▀█ █░░ █▀█ ▄▀█ █▀▄ █▀
  # █▄█ █▀▀ █▄▄ █▄█ █▀█ █▄▀ ▄█

  /api/uploads:
    $ref: 'methods/uploads.yaml#/Base'

  /api/uploads/{id}/metadata:
    $ref: 'methods/uploads.yaml#/AddMetadata'

  /api/uploads/{id}:
    $ref: 'methods/uploads.yaml#/Delete'

  /api/uploads/{id}/apply:
    $ref: 'methods/uploads.yaml#/Apply'

  /api/uploads/tracks/{id}:
    $ref: 'methods/uploads.yaml#/GetUploadedTracks'

  # ▀█▀ █▀█ ▄▀█ █▀▀ █▄▀ █▀
  # ░█░ █▀▄ █▀█ █▄▄ █░█ ▄█

  /api/tracks:
    $ref: 'methods/tracks.yaml#/Base'

  /api/tracks/{id}:
    $ref: 'methods/tracks.yaml#/Id'

  /api/tracks/artists/{id}:
    $ref: 'methods/tracks.yaml#/ByArtist'

  /api/tracks/{id}/similar:
    $ref: 'methods/tracks.yaml#/Similar'

  /api/tracks/search:
    $ref: 'methods/tracks.yaml#/Search'

  /api/tracks/random:
    $ref: 'methods/tracks.yaml#/Random'

  /api/tracks/newest:
    $ref: 'methods/tracks.yaml#/Newest'

  /api/tracks/{id}/lyrics:
    $ref: 'methods/lyrics.yaml#/Get'

  /api/tracks/{id}/lyrics/check:
    $ref: 'methods/lyrics.yaml#/Check'

  /api/tracks/{id}/download:
    $ref: 'methods/tracks.yaml#/Download'

  /api/tracks/{id}/cover:
    $ref: 'methods/tracks.yaml#/Cover'

  /api/tracks/{id}/stream:
    $ref: 'methods/tracks.yaml#/Stream'

  # █▀█ █▀▀ █░░ ▄▀█ ▀█▀ █▀▀ █▀▄   ▀█▀ █▀█ ▄▀█ █▀▀ █▄▀ █▀
  # █▀▄ ██▄ █▄▄ █▀█ ░█░ ██▄ █▄▀   ░█░ █▀▄ █▀█ █▄▄ █░█ ▄█

  /api/tracks/{id}/related:
    $ref: 'methods/relatedTracks.yaml#/Base'

  # █░█ █▀ █▀▀ █▀█ █▀
  # █▄█ ▄█ ██▄ █▀▄ ▄█

  /api/users:
    $ref: 'methods/users.yaml#/Base'

  /api/users/{id}:
    $ref: 'methods/users.yaml#/Id'

  /api/users/{id}/pfp:
    $ref: 'methods/users.yaml#/Image'

  /api/users/me:
    $ref: 'methods/users.yaml#/Me'
  
  /api/users/username/{username}/exists:
    $ref: 'methods/users.yaml#/CheckUsername'




components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization